### ISSUE TITLE
Setting Could you elaborate on the thank you

### ISSUE THREAD

**Issue by 1522402210** [anandtiwarics/archerysec#2]
Zap Setting

Go to Setting Page
Edit ZAP setting or navigate URL : http://host:port/setting_edit/
Fill all required information and click on save.
OpenVAS Setting

Go to setting Page
Edit OpenVAS setting or navigate URL : http://host:port/networkscanners/openvas_setting
Fill all required information and click on save.

**Comment by anandtiwarics** [comment]
These are zap and OpenVAS setting that you need to setup in archery tool.

**Comment by Jamalmo** [comment]
The description is too simple, do not know how to write the configuration file, the host option is written in the old version of the path, the new version into ip, there is no specification, it is recommended to a sample file

**Comment by anandtiwarics** [comment]
Hi,

Still the development in progress and try to make as simple as possible. For time being you can follow this video to setup zap proxy tool with archery tool.

https://www.youtube.com/watch?v=tkauGIaohK0

simar way you can also setup your OpenVAS (Version 8) 

Thanks.

**Comment by Jamalmo** [comment]
Before you upload this video, I have found that the path should be changed to ip address, the disadvantage is that you have to open zap, this will lead to java background occupied resources too high. openvas now configure ip, user name (such as 'admin'), password, still can not be called normally

**Comment by anandtiwarics** [comment]
You can run ZAP Proxy as daemon mode :

For windows envorement:

C:\Program Files\OWASP
```
zap.bat -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
```
others 

```
zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
```

Now you can access API's on your IP or localhost both. I'll update documentation soon.

we can't do anything with OpenVAS and we have to provide credentials into Archery. Open vas API works only with credentials. If you have any solution please let us know, will work together and make more useful.

Thanks.
